defaults:
  - data: train_data
  - model: fc
  - optimizer: adam
  - mlflow: default
  - _self_
params:
  exp_name: ${model.name}
  models_folder: ${hydra.runtime.cwd}/models/
  model_filename: model
  epoch_num: 3
  device: cpu
