defaults:
  - data: train_data
  - model: fc
  - optimizer: adam
  - mlflow: default
  - tensorboard: default
  - callbacks: default
  - trainer: default
  - _self_
params:
  exp_name: ${model.name}
  model_filename: model
